/*
Copyright (c) 2024-2026 Sebastian Sassi

Permission is hereby granted, free of charge, to any person obtaining a copy of 
this software and associated documentation files (the "Software"), to deal in 
the Software without restriction, including without limitation the rights to 
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
of the Software, and to permit persons to whom the Software is furnished to do 
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all 
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
SOFTWARE.
*/
#pragma once

#include <array>
#include <cassert>
#include <cstddef>
#include <span>
#include <tuple>
#include <utility>

#include "utility.hpp"
#include "indexing.hpp"

namespace zest
{

/**
    @brief Type which communicates that an object has no underlying shape.

    The null shape communicates that a given object has no underlying shape. It
    is primarily used in subshape hierarchies to indicate that we have reached
    the bottom of the hierarchy. All shapes of rank \f$N\f$ should have it as
    its \f$N\f$th subshape.
*/
class NullShape
{
public:
    using size_type = std::size_t;
    using index_type = size_type;
    using index_range = SingleIndexRange<index_type>;
    using extent_type = size_type;

    static constexpr size_type rank = 0;
    static constexpr std::size_t linear_extent = 0;

    /**
        @brief Subshapes of the shape.
    */
    template <std::size_t N>
        requires (N > 0)
    using subshape_type = NullShape;

    constexpr NullShape() = default;

    /**
        @brief Construct a shape from extents.
    */
    explicit constexpr NullShape(extent_type /*unused*/) {}

    /**
        @brief Size of the shape for given extents.

        @return Always returns zero.
    */
    [[nodiscard]] static constexpr size_type
    size([[maybe_unused]] extent_type /*unused*/) noexcept { return 0; }

    /**
        @brief Size of the shape.

        @return Always returns zero.
    */
    [[nodiscard]] static constexpr size_type
    size() noexcept { return 0; }

    /**
        @brief Extents of the shape.

        @return Always returns zero.
    */
    [[nodiscard]] static constexpr extent_type
    extents() noexcept { return 0; }

    /**
        @brief Index range of the shape.

        @return Returns a range with a single index zero.
    */
    [[nodiscard]] static constexpr index_range
    indices() noexcept { return index_range{}; }
};

/**
    @brief Concept for checking if a type looks like a shape.
*/
template <typename T>
concept shape = requires (T x, typename T::extent_type ex, typename T::index_type ind)
    {
        { T::size(ex) } -> std::same_as<typename T::size_type>;
        { x.size() } -> std::same_as<typename T::size_type>;
        { x.extents() } -> std::same_as<typename T::extent_type>;
        { x.indices() } -> std::same_as<typename T::index_range>;
        { x.indices(ind) } -> std::same_as<typename T::index_range>;
    }
    && std::same_as<decltype(T::rank), typename T::size_type>
    && std::same_as<decltype(T::linear_extent), typename T::size_type>
    && std::same_as<typename T::template subshape_type<T::rank>, NullShape>;

/**
    @brief Shape which is generated by an infinite sequence.

    @tparam SequenceType Type of generating sequence.

    Some shapes can be naturally regarded as being generated by an infinite
    sequence of index tuples, such that they can be fully specified by a
    single number. An example of such a sequence is the sequence of index pairs
    \f$(l, m)\f$ with \f$|m| \leq l\f$, which can be naturally mapped to a 
    contiquous sequence via \f$l(l + 1) + m\f$, such that only the cutoff for
    the index \f$l\f$ needs to be know to get a finite shape.

    Concretely, the shape is described by a single number, the order, such that
    the index of its outermost dimension is less than the order.

    All subshapes of sequenced shapes are, by definition, also sequenced shapes.
*/
template <typename SequenceType>
class SequencedShape
{
public:
    using sequence_type = SequenceType;
    using size_type = typename sequence_type::size_type;
    using index_type = typename sequence_type::index_type;
    using index_range = typename sequence_type::index_range;
    using extent_type = size_type;

    static constexpr size_type rank = sequence_type::rank;
    static constexpr std::size_t linear_extent = std::dynamic_extent;

private:
    template <std::size_t N> struct subshape_helper;

    template <std::size_t N>
        requires (0 < N && N < rank)
    struct subshape_helper<N>
    {
        using type = SequencedShape<typename sequence_type::template subsequence_type<N>>;
    };

    template <std::size_t N>
        requires (N == rank)
    struct subshape_helper<N>
    {
        using type = NullShape;
    };

public:

    /**
        @brief Subshapes of the shape.
    */
    template <std::size_t N>
        requires (0 < N && N <= rank)
    using subshape_type = subshape_helper<N>::type;

    constexpr SequencedShape() = default;

    /**
        @brief Construct a sequenced shape from its order.

        @param Order of the sequenced shape.
    */
    explicit constexpr SequencedShape(extent_type order):
        m_order{order}, m_size{size(order)} {}


    /**
        @brief Size of the sequenced shape for a given order.

        @param Order of the sequenced shape.
    */
    [[nodiscard]] static constexpr size_type
    size(extent_type order) noexcept { return sequence_type::size(order); }

    /**
        @brief Size of the shape.
    */
    [[nodiscard]] constexpr size_type
    size() const noexcept { return m_size; }

    /**
        @brief Extent of the shape.
    */
    [[nodiscard]] constexpr extent_type
    extents() const noexcept { return m_order; }

    /**
        @brief Order paramter of the shape; synonymous to `extents()`.
    */
    [[nodiscard]] constexpr extent_type
    order() const noexcept { return m_order; }


    /**
        @brief Subshape of the shape.

        @param indices Indices at which the subshape is taken.
    */
    template <std::integral... Inds>
        requires (1 <= sizeof...(Inds) && sizeof...(Inds) < rank)
    [[nodiscard]] constexpr auto
    subshape(Inds... indices) const noexcept
    {
        return subshape_type<sizeof...(Inds)>{
            sequence_type::subextent(index_type(indices)...)
        };
    }

    template <std::integral... Inds>
        requires (sizeof...(Inds) == rank)
    [[nodiscard]] constexpr auto
    subshape([[maybe_unused]] Inds... indices) const noexcept
    {
        return NullShape{};
    }

    /**
        @brief Get the contiguous index corresponding to the shape indices.

        @param indices Indices mapped to the contiquous sequence.
    */
    template <std::integral... Inds>
        requires (1 <= sizeof...(Inds) && sizeof...(Inds) <= rank)
    [[nodiscard]] constexpr index_type
    operator()(Inds... indices) const noexcept
    {
        return sequence_type::index(index_type(indices)...);
    }

    /**
        @brief Index range of the shape.
    */
    [[nodiscard]] constexpr index_range
    indices() const noexcept { return index_range{index_type{m_order}}; }

    /**
        @brief Index range of the shape starting at a given index.

        @brief index Starting index.
    */
    [[nodiscard]] constexpr index_range
    indices(index_type index) const noexcept
    {
        return index_range{index, index_type{index_type{m_order}}};
    }

private:
    extent_type m_order{};
    size_type m_size{};
};

namespace detail
{

template <std::size_t... static_extents, std::size_t N>
[[nodiscard]] constexpr std::array<std::size_t, sizeof...(static_extents)>
combine(const std::array<std::size_t, N>& dynamic_extents) noexcept
{
    auto impl = [&]<std::size_t... I>(std::index_sequence<I...>)
    {
        std::size_t i = 0;
        std::array<std::size_t, sizeof...(static_extents)> extents{};
        ([&](){
            if constexpr (static_extents == std::dynamic_extent)
            {
                extents[I] = dynamic_extents[i];
                ++i;
            }
            else
                extents[I] = static_extents;
        }(),...);
        return extents;
    };
    return impl(std::make_index_sequence<sizeof...(static_extents)>{});
}

template <std::size_t... static_extents>
[[nodiscard]] constexpr std::size_t
count(std::size_t n) noexcept
{
    return (std::size_t(static_extents == n) + ...);
}

template <std::size_t... static_extents>
[[nodiscard]] constexpr std::array<std::size_t, count<static_extents...>(std::dynamic_extent)>
extract_dynamic(const std::array<std::size_t, sizeof...(static_extents)>& extents)
{
    static constexpr std::size_t num_dynamic = count<static_extents...>(std::dynamic_extent);
    auto impl = [&]<std::size_t... I>(std::index_sequence<I...>)
    {
        std::size_t i = 0;
        std::array<std::size_t, num_dynamic> res{};
        ([&](){
            if constexpr (static_extents == std::dynamic_extent)
            {
                res[i] = extents[static_extents];
                ++i;
            }
        }(),...);
        return res;
    };
    return impl(std::make_index_sequence<sizeof...(static_extents)>{});
}

} // namespace detail

/**
    @brief Shape describing the layout of a general multidimensional array.

    @tparam extent_params Parameters describing the extents of the array.

    This class describes the shape of multidimensional arrays/tensors. It
    allows tensor shapes may be known at compile time (static) or may only be
    known at runtime (dynamic). Thus any of the `extent_params` having the
    value `std::dynamic_extent` corresponds to a dynamic dimension, while any
    other value corresponds to a static dimension of the given size.
*/
template <std::size_t... extent_params>
class TensorShape
{
public:
    using size_type = std::size_t;
    using index_type = size_type;
    using index_range = StandardIndexRange<size_type>;
    using extent_type = std::array<size_type, sizeof...(extent_params)>;
    using dynamic_extent_type
        = std::array<size_type, detail::count<extent_params...>(std::dynamic_extent)>;

    static constexpr size_type rank = sizeof...(extent_params);
    static constexpr size_type dynamic_rank
        = detail::count<extent_params...>(std::dynamic_extent);
    static constexpr std::size_t linear_extent = std::dynamic_extent;
    static constexpr std::array<std::size_t, sizeof...(extent_params)> static_extents
        = {extent_params...};

private:
    template <std::size_t N, typename T>
    struct subshape_helper;

    template <std::size_t N, std::size_t... Inds>
        requires (sizeof...(Inds) == rank - N && 1 <= N && N < rank)
    struct subshape_helper<N, std::index_sequence<Inds...>>
    {
        using type = TensorShape<std::get<N + Inds>(static_extents)...>;
    };

    template <std::size_t N>
        requires (N == rank)
    struct subshape_helper<N, std::index_sequence<>>
    {
        using type = NullShape;
    };

public:
    /**
        @brief Subshapes of the shape.
    */
    template <std::size_t N>
        requires (0 < N && N <= rank)
    using subshape_type = subshape_helper<N, std::make_index_sequence<rank - N>>::type;

    constexpr TensorShape() = default;

    /**
        @brief Construct a shape from its extents.
    */
    explicit constexpr TensorShape(const extent_type& extents):
        m_extents{extents}, m_size{size(extents)} {}

    /**
        @brief Construct a shape from its dynamic extents.
    */
    explicit constexpr TensorShape(const dynamic_extent_type& dynamic_extents)
        requires (dynamic_rank != rank):
        m_extents{detail::combine<extent_params...>(dynamic_extents)},
        m_size{size(detail::combine<extent_params...>(dynamic_extents))} {}

    /**
        @brief Construct a shape from its extents.
    */
    template <std::integral... SizeTypes>
        requires (sizeof...(SizeTypes) == rank)
    explicit constexpr TensorShape(SizeTypes... extents):
        m_extents{size_type(extents)...}, m_size{size({size_type(extents)...})} {}

    /**
        @brief Construct a shape from its dynamic extents.
    */
    template <std::integral... SizeTypes>
        requires ((sizeof...(SizeTypes) == dynamic_rank) && (dynamic_rank != rank))
    explicit constexpr TensorShape(SizeTypes... dynamic_extents):
        m_extents{
            detail::combine<extent_params...>(
                dynamic_extent_type{size_type(dynamic_extents)...})
        },
        m_size{
            size(
                detail::combine<extent_params...>(
                    dynamic_extent_type{size_type(dynamic_extents)...}))
        } {}

    /**
        @brief Size of the shape given its extents.
    */
    [[nodiscard]] static constexpr size_type
    size(const extent_type& extents) noexcept { return product(extents); }

    /**
        @brief Size of the shape given its dynamic extents.
    */
    [[nodiscard]] static constexpr size_type
    size(const dynamic_extent_type& dynamic_extents) noexcept requires (dynamic_rank != rank)
    {
        return product(detail::combine<extent_params...>(dynamic_extents));
    }

    /**
        @brief Size of the shape given its extents.
    */
    template <std::integral... SizeTypes>
        requires (sizeof...(SizeTypes) == rank)
    [[nodiscard]] static constexpr size_type
    size(SizeTypes... extents) noexcept
    {
        return product(extent_type{size_type(extents)...});
    }

    /**
        @brief Size of the shape given its dynamic extents.
    */
    template <std::integral... SizeTypes>
        requires (sizeof...(SizeTypes) == detail::count<extent_params...>(std::dynamic_extent))
    [[nodiscard]] static constexpr size_type
    size(SizeTypes... dynamic_extents) noexcept
    {
        return product(
            detail::combine<extent_params...>(
                dynamic_extent_type{size_type(dynamic_extents)...}));
    }

    /**
        @brief Size of the shape.
    */
    [[nodiscard]] constexpr size_type
    size() const noexcept { return m_size; }

    /**
        @brief Extents of the shape.
    */
    [[nodiscard]] constexpr const extent_type&
    extents() const noexcept { return m_extents; }

    /**
        @brief Dynamic extents of the shape.
    */
    [[nodiscard]] constexpr dynamic_extent_type
    dynamic_extents() const noexcept
    {
        detail::extract_dynamic<extent_params...>(m_extents);
    }

    /**
        @brief Extent of the shape along a given dimension.
    */
    [[nodiscard]] constexpr size_type
    extent(size_type i) const noexcept { return m_extents[i]; }

    /**
        @brief Extent of the shape along a given dimension known at compile
        time.
    */
    template <std::size_t I>
        requires (I < rank)
    [[nodiscard]] constexpr size_type
    extent() const noexcept
    {
        if constexpr (static_extents[I] == std::dynamic_extent)
            return m_extents[I];
        else
            return static_extents[I];
    }

    /**
        @brief Subshape of the shape.

        @param inds Indices at which the subshape is taken.
    */
    template <std::integral... Inds>
        requires (1 <= sizeof...(Inds) && sizeof...(Inds) < rank)
    [[nodiscard]] constexpr auto
    subshape([[maybe_unused]] Inds... inds) const noexcept
    {
        return subshape_type<sizeof...(Inds)>{
                take_last<rank - sizeof...(Inds)>(m_extents)
        };
    }

    template <std::integral... Inds>
        requires (sizeof...(Inds) == rank)
    [[nodiscard]] constexpr auto
    subshape([[maybe_unused]] Inds... inds) const noexcept { return NullShape{}; }

    /**
        @brief Get the contiguous index corresponding to the shape indices.

        @param indices Indices mapped to the contiquous sequence.
    */
    template <std::integral... Inds>
        requires (1 <= sizeof...(Inds) && sizeof...(Inds) <= rank)
    [[nodiscard]] constexpr index_type
    operator()(Inds... indices) const noexcept
    {
        return array::detail::index(m_extents, index_type(indices)...);
    }

    /**
        @brief Index range of the shape.
    */
    [[nodiscard]] constexpr auto
    indices() const noexcept { return index_range{index_type{m_extents[0]}}; }

    /**
        @brief Index range of the shape starting at a given index.

        @brief index Starting index.
    */
    [[nodiscard]] constexpr auto
    indices(index_type index) const noexcept
    {
        return index_range{index, index_type{m_extents[0]}};
    }

private:
    extent_type m_extents{};
    size_type m_size{};
};

namespace detail
{

template <typename T>
struct DynamicTensorShapeHelper;

template <std::size_t... extent_params>
struct DynamicTensorShapeHelper<std::index_sequence<extent_params...>>
{
    using type = TensorShape<(std::dynamic_extent + 0*extent_params)...>;
};

} // namespace detail

/**
    @brief Alias for a `TensorShape` with only dynamic extents.

    @tparam rank Rank of the `TensorShape`.
*/
template <std::size_t rank>
using DynamicTensorShape
    = detail::DynamicTensorShapeHelper<std::make_index_sequence<rank>>::type;

template <std::size_t... extent_params>
    requires ((extent_params != std::dynamic_extent) && ...)
class TensorShape<extent_params...>
{
public:
    using size_type = std::size_t;
    using index_type = size_type;
    using index_range = StandardIndexRange<size_type>;
    using extent_type = std::array<size_type, sizeof...(extent_params)>;
    using dynamic_extent_type = std::array<size_type, 0>;

    static constexpr size_type rank = sizeof...(extent_params);
    static constexpr std::size_t linear_extent = product(std::array{extent_params...});
    static constexpr extent_type static_extents = std::array{extent_params...};

private:
    template <std::size_t N, typename T>
    struct subshape_helper;

    template <std::size_t N, std::size_t... Inds>
        requires (sizeof...(Inds) == rank - N && 1 <= N && N < rank)
    struct subshape_helper<N, std::index_sequence<Inds...>>
    {
        using type = TensorShape<std::get<N + Inds>(static_extents)...>;
    };

    template <std::size_t N>
        requires (N == rank)
    struct subshape_helper<N, std::index_sequence<>>
    {
        using type = NullShape;
    };

public:
    template <std::size_t N>
        requires (0 < N && N <= rank)
    using subshape_type = subshape_helper<N, std::make_index_sequence<rank - N>>::type;

    constexpr TensorShape() = default;
    explicit constexpr TensorShape([[maybe_unused]] const extent_type& extents) {}
    explicit constexpr TensorShape(
        [[maybe_unused]] const dynamic_extent_type& dynamic_extents) {}

    template <std::integral... ExtentTypes>
        requires (sizeof...(ExtentTypes) == rank)
    explicit constexpr TensorShape([[maybe_unused]] ExtentTypes... extents) {}

    [[nodiscard]] static constexpr size_type
    size([[maybe_unused]] const extent_type& extents) noexcept
    {
        return linear_extent;
    }

    [[nodiscard]] static constexpr size_type
    size([[maybe_unused]] const dynamic_extent_type& dynamic_extents) noexcept
    {
        return linear_extent;
    }

    [[nodiscard]] static constexpr size_type
    size() noexcept { return linear_extent; }

    [[nodiscard]] constexpr dynamic_extent_type
    dynamic_extents() const noexcept { return {}; }

    [[nodiscard]] constexpr extent_type
    extents() const noexcept { return static_extents; }

    [[nodiscard]] constexpr size_type
    extent(size_type i) const noexcept { return static_extents[i]; }

    template <std::size_t I>
        requires (I < rank)
    [[nodiscard]] constexpr size_type
    extent() const noexcept
    {
        return static_extents[I];
    }

    template <std::integral... Inds>
        requires (1 <= sizeof...(Inds) && sizeof...(Inds) < rank)
    [[nodiscard]] constexpr auto
    subshape([[maybe_unused]] Inds... inds) const noexcept
    {
        return subshape_type<sizeof...(Inds)>{};
    }

    template <std::integral... Inds>
        requires (sizeof...(Inds) == rank)
    [[nodiscard]] constexpr auto
    subshape([[maybe_unused]] Inds... inds) const noexcept { return NullShape{}; }

    template <std::integral... Inds>
        requires (1 <= sizeof...(Inds) && sizeof...(Inds) <= rank)
    [[nodiscard]] constexpr index_type
    operator()(Inds... indices) const noexcept
    {
        return array::detail::index(static_extents, index_type(indices)...);
    }

    [[nodiscard]] constexpr auto
    indices() const noexcept { return index_range{index_type{static_extents[0]}}; }

    [[nodiscard]] constexpr auto
    indices(index_type index) const noexcept
    {
        return index_range{index, index_type{static_extents[0]}};
    }
};

/**
    @brief Compose an outer shape and an inner shape to a new shape.

    @tparam OuterShape
    @tparam InnerShape
*/
template <typename OuterShape, typename InnerShape>
class CompositeShape
{
public:
    using first_component_type = OuterShape;
    using second_component_type = InnerShape;
    using size_type = typename OuterShape::size_type;
    using index_type = typename OuterShape::index_type;
    using index_range = typename OuterShape::index_range;
    using extent_type
        = std::tuple<typename OuterShape::extent_type, typename InnerShape::extent_type>;

    static constexpr size_type rank = OuterShape::rank + InnerShape::rank;
    static constexpr std::size_t linear_extent
        = (OuterShape::linear_extent == std::dynamic_extent
                || InnerShape::linear_extent == std::dynamic_extent) ?
            std::dynamic_extent : OuterShape::linear_extent*InnerShape::linear_extent;
private:
    template <std::size_t N>
    struct subshape_helper;

    template <std::size_t N>
        requires (N < OuterShape::rank)
    struct subshape_helper<N>
    {
        using type
            = CompositeShape<typename OuterShape::template subshape_type<N>, InnerShape>;
    };

    template <std::size_t N>
        requires (N == OuterShape::rank)
    struct subshape_helper<N>
    {
        using type = InnerShape;
    };

    template <std::size_t N>
        requires (OuterShape::rank < N && N < rank)
    struct subshape_helper<N>
    {
        using type = typename InnerShape::template subshape_type<N - OuterShape::rank>;
    };

    template <std::size_t N>
        requires (N == rank)
    struct subshape_helper<N>
    {
        using type = NullShape;
    };

public:
    /**
        @brief Subshapes of the shape.
    */
    template <std::size_t N>
        requires (N > 0)
    using subshape_type = subshape_helper<N>::type;

    constexpr CompositeShape() = default;

    /**
        @brief Construct a composite shape from the extents of its inner and
        outer shapes.

        @param outer_extents Extents of the outer shape.
        @param inner_extents Extents of the inner shape.
    */
    template <typename E1, typename E2>
        requires std::constructible_from<OuterShape, E1>
            && std::constructible_from<InnerShape, E2>
    constexpr CompositeShape(const E1& outer_extents, const E2& inner_extents):
        m_shapes{OuterShape{outer_extents}, InnerShape{inner_extents}} {}

    /**
        @brief Construct a composite shape with inner static extents from the
        extents of its outer shape.

        @param outer_extents Extents of the outer shape.
    */
    template <typename E>
        requires std::constructible_from<OuterShape, E>
    explicit constexpr CompositeShape(const E& outer_extents)
        requires (OuterShape::linear_extent == std::dynamic_extent
            && InnerShape::linear_extent != std::dynamic_extent):
        m_shapes{OuterShape{outer_extents}, InnerShape{}} {}

    /**
        @brief Construct a composite shape with outer static extents from the
        extents of its inner shape.

        @param inner_extents Extents of the inner shape.
    */
    template <typename E>
        requires std::constructible_from<InnerShape, E>
    explicit constexpr CompositeShape(const E& inner_extents)
        requires (OuterShape::linear_extent != std::dynamic_extent
            && InnerShape::linear_extent == std::dynamic_extent):
        m_shapes{OuterShape{}, InnerShape{inner_extents}} {}

    /**
        @brief Construct a composite shape from its component shapes.
    */
    constexpr CompositeShape(const OuterShape& outer_shape, const InnerShape& inner_shape):
        m_shapes(outer_shape, inner_shape) {}

    /**
        @brief Size of a composite shape given the outer and inner extents.

        @param outer_extents Extents of the outer shape.
        @param inner_extents Extents of the inner shape.
    */
    [[nodiscard]] static constexpr size_type
    size(
        const OuterShape::extent_type& outer_extents,
        const InnerShape::extent_type& inner_extents) noexcept
    {
        return OuterShape::size(outer_extents)*InnerShape::size(inner_extents);
    }

    /**
        @brief Size of a composite shape with inner static extents given the
        extents of its outer shape.

        @param outer_extents Extents of the outer shape.
    */
    [[nodiscard]] static constexpr size_type
    size(const OuterShape::extent_type& outer_extents)
        requires (OuterShape::linear_extent == std::dynamic_extent
            && InnerShape::linear_extent != std::dynamic_extent)
    {
        return OuterShape::size(outer_extents)*InnerShape::linear_extent;
    }

    /**
        @brief Size of a composite shape with outer static extents given the
        extents of its inner shape.

        @param inner_extents Extents of the inner shape.
    */
    [[nodiscard]] static constexpr size_type
    size(const InnerShape::extent_type& inner_extents)
        requires (OuterShape::linear_extent != std::dynamic_extent
            && InnerShape::linear_extent == std::dynamic_extent)
    {
        return OuterShape::linear_extent*InnerShape::size(inner_extents);
    }

    /**
        @brief Size of the shape.
    */
    [[nodiscard]] static constexpr size_type
    size() noexcept requires (linear_extent != std::dynamic_extent) { return linear_extent; }

    [[nodiscard]] constexpr size_type
    size() const noexcept requires (linear_extent == std::dynamic_extent)
    {
        return m_shapes.first.size()*m_shapes.second.size();
    }

    /**
        @brief Order paramter of the shape if the outer shape is a sequenced
        shape.
    */
    [[nodiscard]] constexpr OuterShape::extent_type
    order() const noexcept requires sequence_shaped<OuterShape>
    {
        return m_shapes.first.extents();
    }

    /**
        @brief Extent of the shape at a given index.
    */
    [[nodiscard]] constexpr size_type
    extent(size_type index) const noexcept { return m_shapes.first.extent(index); }

    /**
        @brief Extents of the shape.
    */
    [[nodiscard]] constexpr extent_type
    extents() const noexcept
    {
        return {m_shapes.first.extents(), m_shapes.second.extents()};
    }

    template <std::integral... Inds>
        requires (1 <= sizeof...(Inds) && sizeof...(Inds) < OuterShape::rank)
    [[nodiscard]] constexpr auto
    subshape(Inds... indices) const noexcept
    {
        return subshape_type<sizeof...(Inds)>{
            m_shapes.first.subshape((typename OuterShape::index_type)(indices)...),
            m_shapes.second
        };
    }

    /**
        @brief Subshape of the shape.

        @param indices Indices at which the subshape is taken.
    */
    template <std::integral... Inds>
        requires (sizeof...(Inds) == OuterShape::rank)
    [[nodiscard]] constexpr auto
    subshape([[maybe_unused]] Inds... indices) const noexcept
    {
        return subshape_type<sizeof...(Inds)>{m_shapes.second};
    }

    template <std::integral... Inds>
        requires (OuterShape::rank < sizeof...(Inds) && sizeof...(Inds) < rank)
    [[nodiscard]] constexpr auto
    subshape(Inds... indices) const noexcept
    {
        auto impl = [&]<std::size_t... I, typename T>(std::index_sequence<I...>, T index_tuple)
        {
            return subshape_type<sizeof...(Inds)>{
                m_shapes.second.subshape(std::get<OuterShape::rank + I>(index_tuple)...)
            };
        };
        return impl(
            std::make_index_sequence<sizeof...(Inds) - OuterShape::rank>{},
            std::make_tuple(indices...));
    }

    template <std::integral... Inds>
        requires (sizeof...(Inds) == rank)
    [[nodiscard]] constexpr auto
    subshape([[maybe_unused]] Inds... indices) const noexcept
    {
        return subshape_type<sizeof...(Inds)>(NullShape{});
    }

    /**
        @brief Get the contiguous index corresponding to the shape indices.

        @param indices Indices mapped to the contiquous sequence.
    */
    template <std::integral... Inds>
        requires (1 <= sizeof...(Inds) && sizeof...(Inds) <= rank)
    [[nodiscard]] constexpr index_type
    operator()(Inds... indices) const noexcept { return index(index_type(indices)...); }

    /**
        @brief Index range of the shape.
    */
    [[nodiscard]] constexpr index_range
    indices() const noexcept { return m_shapes.first.indices(); }

    /**
        @brief Index range of the shape starting at a given index.

        @brief index Starting index.
    */
    [[nodiscard]] constexpr index_range
    indices(index_type index) const noexcept { return m_shapes.first.indices(index); }

private:
    template <std::integral... Inds>
        requires (1 <= sizeof...(Inds) && sizeof...(Inds) <= OuterShape::rank)
    [[nodiscard]] constexpr index_type
    index(Inds... indices) const noexcept
    {
        using outer_index_type = typename OuterShape::index_type;
        return m_shapes.first(outer_index_type(indices)...)*m_shapes.second.size();
    }

    template <std::integral... Inds>
        requires (OuterShape::rank < sizeof...(Inds) && sizeof...(Inds) <= rank)
    [[nodiscard]] constexpr index_type
    index(Inds... indices) const noexcept
    {
        auto impl = [&]<std::size_t... I, std::size_t... J, typename T>
        (std::index_sequence<I...>, std::index_sequence<J...>, T index_tuple)
        {
            using outer_index_type = typename OuterShape::index_type;
            using inner_index_type = typename InnerShape::index_type;
            return m_shapes.first(
                    outer_index_type(std::get<I>(index_tuple))...)*m_shapes.second.size()
                + m_shapes.second(
                    inner_index_type(std::get<OuterShape::rank + J>(index_tuple))...);
        };
        return impl(
            std::make_index_sequence<OuterShape::rank>{},
            std::make_index_sequence<sizeof...(Inds) - OuterShape::rank>{},
            std::make_tuple(indices...));
    }

    std::pair<OuterShape, InnerShape> m_shapes{};
};

/**
    @brief Alias for a shape describing a sequenced shape of tensor shapes.

    @tparam SequenceType Type of the outer sequenced shape.
    @tparam extent_params Inner tensor shape extents.
*/
template <typename SequenceType, std::size_t... extent_params>
using TensorSequenceShape = std::conditional_t<(sizeof...(extent_params) > 0),
    CompositeShape<SequencedShape<SequenceType>, TensorShape<extent_params...>>,
    SequencedShape<SequenceType>>;

/**
    @brief Alias for a shape describing a tensor of sequenced shapes.

    @tparam SequenceType Type of the inner sequenced shape.
    @tparam extent_params Outer tensor shape extents.
*/
template <typename SequenceType, std::size_t... extent_params>
using SequenceTensorShape = std::conditional_t<(sizeof...(extent_params) > 0),
    CompositeShape<TensorShape<extent_params...>, SequencedShape<SequenceType>>,
    SequencedShape<SequenceType>>;

/**
    @brief Helper type for attaching arbitrary tag types to shapes.

    @tparam ShapeType Shape to be tagged.
    @tparam Tags Types tagging the shape type.
*/
template <typename ShapeType, tag_type... Tags>
struct TaggedShape: public ShapeType, public Tags...
{
    using untag = ShapeType;

    template <std::size_t N>
    using subshape_type = TaggedShape<typename ShapeType::template subshape_type<N>, Tags...>;

    using ShapeType::ShapeType;

    explicit TaggedShape(const ShapeType& other): ShapeType(other) {}
};

} // namespace zest
